on: 
  push:
    paths-ignore:
      - '**/*.md'

permissions:
  id-token: write
  contents: read

env:
  AWS_OIDC_ROLE_ARN: ${{ secrets.AWS_OIDC_ROLE_ARN }}
  AWS_REGION: ap-northeast-1

jobs:
  aws-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Assume Role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.AWS_OIDC_ROLE_ARN }}
          aws-region: ${{env.AWS_REGION}}

      - name: Cache CDK Dependency
        uses: actions/cache@v3
        id: cache_cdk_dependency_id
        env:
          cache-name: cache-cdk-dependency
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
          restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-

      - name: Install CDK Dependency
        if: ${{ steps.cache_cdk_dependency_id.outputs.cache-hit != 'true' }}
        run: npm install

      # - name: Cache Web Dependency
      #   uses: actions/cache@v3
      #   id: cache_web_dependency_id
      #   env:
      #     cache-name: cache-web-dependency
      #   with:
      #     path: web/node_modules
      #     key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('web/package-lock.json') }}
      #     restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-

      # - name: Install Web Dependency
      #   if: ${{ steps.cache_web_dependency_id.outputs.cache-hit != 'true' }}
      #   run: npm --prefix web install

      # - name: Cache Build Web
      #   uses: actions/cache@v3
      #   id: cache_build_web_id
      #   env:
      #     cache-name: cache-build-web
      #   with:
      #     path: web/build
      #     key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('web/*', '!web/node_modules', '!web/**/*.md', '!web/build') }}

      # - name: Build Web
      #   if: ${{ steps.cache_build_web_id.outputs.cache-hit != 'true' }}
      #   run: npm --prefix web run build

      - name: Deploy
        run: npm run deploy
